/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "STM32F103C8T6.h"

void GPIO_Init(void);
void TIM2_PWM_Init(void);
void LED_Dimming(uint32_t step);

int main(void)
{
    /* Initial PTA0 as PWM output pin */
    GPIO_Init();
    /* Initial TIM2 as PWM mode 1 */
    TIM2_PWM_Init();

    while (1)
    {
    	LED_Dimming(10);
    }
}

void GPIO_Init(void)
{

}

void TIM2_PWM_Init(void)
{
    /* Enable clock for TIM2 */
    RCC->APB1ENR |= RCC_APB1ENR_TIM2EN(1u);

    /**
     * Setup clock frequency for TIM2. When POR (power of reset):
     * RCC_CR:      Reset value: 0x0000 XX83:   HSION and HSIRDY -> clock source is HSI (8MHz)
     * RCC_CFRG:    Reset value: 0x0
     *      + PLLSRC = 0 -> HSI oscillator clock / 2 selected as PLL input clock (4MHz)
     *      + PLLMUL = 0 -> PLL input clock * 2 (8MHz)
     *      + SW = 0 ->  HSI selected as system clock (8MHz)
     *      + HPRE = 0 -> SYSCLK not divided
     *      + PPRE1 = 0 -> HCLK not divided
     * Summary: PCLK1 = 8MHz
     */

    /* Set PSR = 7 -> Fclock = CK_PSC / (PSC[15:0] + 1) = 8 / (7 + 1) = 1MHz */
    TIM2->PSC = TIM_PSC_PSC(7u);
    TIM2->ARR = TIM_ARR_ARR(0xFFFFu);

    /* Enable counter */
    TIM2->CR1 |= TIM_CR1_CEN(1u);
}

void LED_Dimming(uint32_t step)
{

}
