/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

/**
 * Program to blink PC13 LED using button
 * Button was connected to PTA0 and GND
 * PTA0 was configured as input, pull-up
 * Press button -> input data = GND = 0
 */

#include "STM32F103C8T6.h"

#define EXTI0_IRQNumber     (6u)

int main(void)
{
    uint32_t irq_index = EXTI0_IRQNumber / 32;
    uint32_t irq_pos   = EXTI0_IRQNumber % 32;
    /* Enable clock for port C */
    RCC->APB2ENR |= RCC_APB2ENR_IOPCEN(1u);

    /* Set PC13 to GPIO output and push-pull mode */
    GPIOC->CRH &= ~GPIO_CRH_MODE13_MASK;
    GPIOC->CRH &= ~GPIO_CRH_CNF13_MASK;
    GPIOC->CRH |= (0x2 << GPIO_CRH_MODE13_SHIFT) | GPIO_CRH_CNF13(0);

    /* Set 1 to OFF PC13 LED */
    GPIOC->BSRR |= GPIO_BSRR_BS13_MASK;

    /* Enable clock for port A */
    RCC->APB2ENR |= RCC_APB2ENR_IOPAEN(1u);

    /* Set PTA0 to GPIO input */
    GPIOA->CRL &= ~GPIO_CRL_MODE0_MASK;
    /* Set PTA0 input with pull-up/pull-down */
    GPIOA->CRL &= ~GPIO_CRL_CNF0_MASK;
    GPIOA->CRL |= GPIO_CRL_CNF0(2u);
    /* Set ODR to 1 to select pull-up */
    /* Refer Table 20. Port bit configuration table */
    GPIOA->ODR |= GPIO_BSRR_BS0(1u);

    /**
     * Configure EXTI for line 0 (button was connect to PTA0, pull-up)
     * Press button -> data change from 1 to 0, so setup interrupt but falling edge
     */
    EXTI->FTSR |= EXTI_FTSR_TR0_MASK;   /* falling edge */
    EXTI->IMR  |= EXTI_IMR_MR0_MASK;    /* enable interrupt for line 0 */

    /**
     * Setup NVIC block: Clear pending for EXTI0 and set IRQ enable
     * This program use only 1 IRQ, no priority set up is needed
     */
    NVIC->ICPR[irq_index] &= ~(1u << irq_pos);
    NVIC->ISER[irq_index] |= (1u << irq_pos);

    /* Loop forever */
    while (1)
    {
    }
}

void EXTI0_IRQHandler(void)
{
    uint32_t index;

    /* Clear pending flag */
    EXTI->PR   |= EXTI_PR_PR0_MASK;

    /* Debounce */
    for (index = 0; index < 10000; index++);

    /* Toggle PC13 */
    GPIOC->ODR ^= GPIO_ODR_ODR13_MASK;
}
