/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "STM32F103C8T6.h"

int main(void)
{
    /* Enable clock for port C */
    RCC->APB2ENR |= RCC_APB2ENR_IOPCEN(1u);

    GPIOC->CRH &= ~GPIO_CRH_MODE13_MASK;
    GPIOC->CRH &= ~GPIO_CRH_CNF13_MASK;
    /* Set PC13 to  GPIO output and push-pull mode */
    GPIOC->CRH |= (0x2 << GPIO_CRH_MODE13_SHIFT) | GPIO_CRH_CNF13(0);

    /* Set 1 to OFF PC13 LED */
    GPIOC->BSRR |= GPIO_BSRR_BS13_MASK;
    /* Clear to ON PC13 LED */
    GPIOC->BSRR |= GPIO_BSRR_BR13_MASK;

    /* Loop forever */
    for(;;);
}
