/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
*/

#include <stdint.h>

/* Define to access RCC peripheral registers */
#define RCC_BASE_ADDR               (0x40021000u)
#define RCC_APB2ENR_OFFSET          (0x18u)
#define RCC_APB2ENR_ADDR            (RCC_BASE_ADDR + RCC_APB2ENR_OFFSET)

/* Define to access GPIO peripheral registers */
#define GPIO_BASE_ADDR              (0x40011000u)
#define GPIO_CRH_OFFSET             (0x04u)
#define GPIO_CRH_ADDR               (GPIO_BASE_ADDR + GPIO_CRH_OFFSET)
#define GPIO_ODR_OFFSET             (0x0Cu)
#define GPIO_ODR_ADDR               (GPIO_BASE_ADDR + GPIO_ODR_OFFSET)

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
    uint32_t *RCC_APB2ENR = (uint32_t *)RCC_APB2ENR_ADDR;
    uint32_t *GPIO_CRH    = (uint32_t *)GPIO_CRH_ADDR;
    uint32_t *GPIO_ODR    = (uint32_t *)GPIO_ODR_ADDR;

    /* Enable clock for Port C */
    *RCC_APB2ENR |= (1u << 4);

    /* Configure PC13 pin to GPIO output */
    *GPIO_CRH |= (0x2 << 20) | (1 << 22);

    /* Clear to 0 to turn-on PC13 led */
    *GPIO_ODR &= ~(1u << 13);

    /* Set to 1 to turn-off PC13 led */
    *GPIO_ODR |= (1u << 13);

    /* Loop forever */
    while (1)
    {

    };
}
