/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "STM32F103C8T6.h"

void GPIO_Init(void);
void UART_Init();
void UART_SendCharacter(uint8_t data);
void UART_SendString(uint8_t str[], uint32_t len);

int main(void)
{

    GPIO_Init();


    while (1)
    {

    }
}

void GPIO_Init(void)
{

}
