/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "STM32F103C8T6.h"

uint32_t str_len(uint8_t str[]);

void sys_init(void);
void GPIO_Init(void);
void UART_Init(void);
void UART_SendCharacter(uint8_t character);
void UART_SendString(uint8_t str[], uint32_t len);

int main(void)
{
    uint8_t str[] = "Hello, Kensin\n";
    /* Set up SYSTEM clock with Fmax = 72 MHz */
    sys_init();
    /**
     * Setup USART1 for RX and TX pin
     * PA9:  USART1_TX: ALT push-pull
     * PA10: USART1_RX: input floating, because CP2102 already has pull-up register
     */
    GPIO_Init();

    UART_Init();

    UART_SendString(str, str_len(str));


    while (1)
    {

    }
}

uint32_t str_len(uint8_t str[])
{
    uint32_t len = 0;

    while ('\0' != str[len])
    {
        len++;
    }

    return len;
}

void sys_init()
{
    /**
     * From schematic of Blue Pill, OSC_IN and OSC_OUT has Y2 = 8 MHz
     * This is a clock source for HSE.
     * So HSE in STM32F103 is 8 MHz
     */
    RCC->CR |= RCC_CR_HSEON_MASK;               /* Enable HSE */
    while (!(RCC->CR & RCC_CR_HSERDY_MASK));    /* Wait HSE stable */

    /* Configure PLL source */
    RCC->CFGR2 &= ~RCC_CFGR2_PREDIV1SRC_MASK;   /* Select PREDIV1SRC is HSE */
    RCC->CFGR2 &= ~RCC_CFGR2_PREDIV1_MASK;      /* Set PREDIV1 = 1 -> F = 8/1 = 8 */
    RCC->CFGR |= RCC_CFGR_PLLSRC_MASK;          /* Select PLLSRC is PREDIV 1 */

    /* Configure PLLMUL before enable PLL clock */
    RCC->CFGR &= ~RCC_CFGR_PLLMUL_MASK;
    RCC->CFGR |= RCC_CFGR_PLLMUL(7u);           /* Set PLLMUL = 9 -> F = 8 * 9 = 72 MHz */

    /* Enable PLL */
    RCC->CR |= RCC_CR_PLLON_MASK;               /* Enable PLL */
    while (!(RCC->CR & RCC_CR_PLLRDY_MASK));    /* Wait PLL stable */

    RCC->CFGR &= ~RCC_CFGR_HPRE_MASK;           /* Set AHB prescaler = 1 */
    RCC->CFGR &= ~RCC_CFGR_PPRE1_MASK;          /* Max PCLK1 is 36 MHz -> set APB1 prescale = 2 */
    RCC->CFGR |= RCC_CFGR_PPRE1(4u);
    RCC->CFGR &= ~RCC_CFGR_PPRE2_MASK;          /* Set APB2 prescaler = 1 */

    /* Select SYSCLOCK input is PLLSRC */
    RCC->CFGR &= ~RCC_CFGR_SW_MASK;
    RCC->CFGR |= RCC_CFGR_SW(2u);
}

void GPIO_Init(void)
{
    /* Enable clock for port A */
    RCC->APB2ENR |= RCC_APB2ENR_IOPAEN_MASK;

    /* PA9: ALT output push-pull */
    GPIOA->CRH &= ~(GPIO_CRH_MODE9_MASK | GPIO_CRH_CNF9_MASK);
    GPIOA->CRH |= GPIO_CRH_MODE9(2u);       /* output, max speed 2MHz */
    GPIOA->CRH |= GPIO_CRH_CNF9(2u);        /* ALT output push-pull */

    /* PA10: input floating point */
    GPIOA->CRH &= ~GPIO_CRH_MODE10_MASK;    /* input mode */
    GPIOA->CRH &= ~GPIO_CRH_CNF10_MASK;
    GPIOA->CRH |= GPIO_CRH_CNF10(1u);       /* floating input */
}

void UART_Init(void)
{
    /* Enable clock for USART1 */
    RCC->APB2ENR |= RCC_APB2ENR_USART1EN_MASK;

    /**
     * USART1: belongs to APB2: max = 72 MHz
     * Configure baudrate = 9600 bps
     * By RM: TX/RX baud = Fclk / (16 * USARTDIV)
     * 9600 = 72 Mhz / (16 * USARTDIV) => USARTDIV = 468.75
     * Mantissa = 468
     * Fraction = 0.75 * 16 = 12
     */
    USART1->BRR = 72000000u / 9600u;

    // USART1->BRR |= UART_BRR_FRAC(12);
    // USART1->BRR |= UART_BRR_MANTISSA(468);

    USART1->CR1 &= ~UART_CR1_M_MASK;        /* word len = 8 bits */
    USART1->CR1 &= ~UART_CR1_PCE_MASK;      /* disable parity */

    USART1->CR1 |= UART_CR1_TE_MASK;        /* transmitter enable */
    USART1->CR1 |= UART_CR1_RE_MASK;        /* receiver enable */

    USART1->CR1 |= UART_CR1_UE_MASK;        /* Enable UART */

    /* Ensure all frame has complete */
    while (!(USART1->SR & UART_SR_TC_MASK));
}

void UART_SendCharacter(uint8_t character)
{
    while (!(USART1->SR & UART_SR_TXE_MASK));       /* wait until TX buffer empty */
    USART1->DR = character;
}

void UART_SendString(uint8_t str[], uint32_t len)
{
    uint32_t i;

    for (i = 0; i <= len; i++)
    {
        UART_SendCharacter(str[i]);
    }
}
