/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

/**
 * Program to blink PC13 LED using button
 * Button was connected to PTA0 and GND
 * PTA0 was configured as input, pull-up
 * Press button -> input data = GND = 0
 */

#include "STM32F103C8T6.h"

int main(void)
{
    uint32_t index = 0;
    uint32_t press = 0;
    /* Enable clock for port C */
    RCC->APB2ENR |= RCC_APB2ENR_IOPCEN(1u);

    /* Set PC13 to GPIO output and push-pull mode */
    GPIOC->CRH &= ~GPIO_CRH_MODE13_MASK;
    GPIOC->CRH &= ~GPIO_CRH_CNF13_MASK;
    GPIOC->CRH |= (0x2 << GPIO_CRH_MODE13_SHIFT) | GPIO_CRH_CNF13(0);

    /* Set 1 to OFF PC13 LED */
    GPIOC->BSRR |= GPIO_BSRR_BS13_MASK;

    /* Enable clock for port A */
    RCC->APB2ENR |= RCC_APB2ENR_IOPAEN(1u);

    /* Set PTA0 to GPIO input */
    GPIOA->CRL &= ~GPIO_CRL_MODE0_MASK;
    /* Set PTA0 input with pull-up/pull-down */
    GPIOA->CRL &= ~GPIO_CRL_CNF0_MASK;
    GPIOA->CRL |= GPIO_CRL_CNF0(2u);
    /* Set ODR to 1 to select pull-up */
    /* Refer Table 20. Port bit configuration table */
    GPIOA->ODR |= GPIO_BSRR_BS0(1u);

    /* Loop forever */
    while (1)
    {
        /* Read PTA0 */
        press = (GPIOA->IDR) & GPIO_IDR_IDR0_MASK;

        if (0 == press)
        {
            for(index = 0; index<200000; index++);  /* debounce */
            if (0 == press)
            {
                GPIOC->ODR ^= GPIO_ODR_ODR13_MASK;
            }
        }
    }
}
